name: GitOPS pipeline with monitoring, observerbility and alert

on:
  push:
    branches:
      - main

env:
  ARGOCD_PASSWORD: ${{secrets.ARGOCD_PASSWORD}}
  ARGOCD_SERVER: ${{secrets.ARGOCD_SERVER}}
  ARGOCD_USERNAME: ${{secrets.ARGOCD_USERNAME}}
  DOCKERHUB_TOKEN: ${{secrets.DOCKERHUB_TOKEN}}
  DOCKERHUB_USERNAME: ${{secrets.DOCKERHUB_USERNAME}}
  PERSONAL_ACCESS_TOKEN: ${{secrets.PERSONAL_ACCESS_TOKEN}}

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: checkout-code
        uses: actions/checkout@v3
        with:
          token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          fetch-depth: 0

      - name: Set up NodeJs
        uses: actions/setup-node@v3
        with:
          node-version: "14"

      - name: Install NodeJS dependancies
        run : npm install

      - name: Deploy
        uses : peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{secrets.PERSONAL_ACCESS_TOKEN}}
          publish_dir: ./Frontend/